
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import DarkForestContractArtifactJson from '../../target/darkforest-DarkForest.json' with { type: 'json' };
export const DarkForestContractArtifact = loadContractArtifact(DarkForestContractArtifactJson as NoirCompiledContract);


      export type PlayerInitialized = {
        player: AztecAddressLike
home_planet: FieldLike
      }
    

      export type PlanetUpgraded = {
        planet_id: FieldLike
branch: (bigint | number)
new_level: (bigint | number)
      }
    

      export type PlanetMoved = {
        from: FieldLike
to: FieldLike
owner: AztecAddressLike
distance: (bigint | number)
      }
    

      export type LocationRevealed = {
        planet_id: FieldLike
x: FieldLike
y: FieldLike
revealer: AztecAddressLike
      }
    

      export type ArtifactFound = {
        planet_id: FieldLike
artifact_id: FieldLike
artifact_type: (bigint | number)
rarity: (bigint | number)
discoverer: AztecAddressLike
      }
    

/**
 * Type-safe interface for contract DarkForest;
 */
export class DarkForestContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, DarkForestContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): DarkForestContract {
    return Contract.at(address, DarkForestContract.artifact, wallet) as DarkForestContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, world_radius: (bigint | number), planethash_key: FieldLike, spacetype_key: FieldLike, perlin_length_scale: (bigint | number), init_perlin_min: (bigint | number), init_perlin_max: (bigint | number)) {
    return new DeployMethod<DarkForestContract>(PublicKeys.default(), wallet, DarkForestContractArtifact, (instance, wallet) => DarkForestContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, world_radius: (bigint | number), planethash_key: FieldLike, spacetype_key: FieldLike, perlin_length_scale: (bigint | number), init_perlin_min: (bigint | number), init_perlin_max: (bigint | number)) {
    return new DeployMethod<DarkForestContract>(publicKeys, wallet, DarkForestContractArtifact, (instance, wallet) => DarkForestContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof DarkForestContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<DarkForestContract['methods'][M]>
  ) {
    return new DeployMethod<DarkForestContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      DarkForestContractArtifact,
      (instance, wallet) => DarkForestContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return DarkForestContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(DarkForestContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'paused' | 'world_radius' | 'planethash_key' | 'spacetype_key' | 'perlin_length_scale' | 'init_perlin_min' | 'init_perlin_max' | 'perlin_threshold_1' | 'perlin_threshold_2' | 'perlin_threshold_3' | 'reveal_cooldown' | 'planet_count' | 'player_count' | 'artifact_count' | 'artifacts' | 'planet_artifact' | 'players' | 'planets' | 'revealed_x' | 'revealed_y' | 'revealed_revealer' | 'revealed_count' | 'revealed_planet_ids' | 'arrival_count' | 'arrivals' | 'planet_arrival_count' | 'planet_arrivals'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
paused: {
      slot: new Fr(2n),
    },
world_radius: {
      slot: new Fr(3n),
    },
planethash_key: {
      slot: new Fr(5n),
    },
spacetype_key: {
      slot: new Fr(7n),
    },
perlin_length_scale: {
      slot: new Fr(9n),
    },
init_perlin_min: {
      slot: new Fr(11n),
    },
init_perlin_max: {
      slot: new Fr(13n),
    },
perlin_threshold_1: {
      slot: new Fr(15n),
    },
perlin_threshold_2: {
      slot: new Fr(17n),
    },
perlin_threshold_3: {
      slot: new Fr(19n),
    },
reveal_cooldown: {
      slot: new Fr(21n),
    },
planet_count: {
      slot: new Fr(23n),
    },
player_count: {
      slot: new Fr(24n),
    },
artifact_count: {
      slot: new Fr(25n),
    },
artifacts: {
      slot: new Fr(26n),
    },
planet_artifact: {
      slot: new Fr(27n),
    },
players: {
      slot: new Fr(28n),
    },
planets: {
      slot: new Fr(29n),
    },
revealed_x: {
      slot: new Fr(30n),
    },
revealed_y: {
      slot: new Fr(31n),
    },
revealed_revealer: {
      slot: new Fr(32n),
    },
revealed_count: {
      slot: new Fr(33n),
    },
revealed_planet_ids: {
      slot: new Fr(34n),
    },
arrival_count: {
      slot: new Fr(35n),
    },
arrivals: {
      slot: new Fr(36n),
    },
planet_arrival_count: {
      slot: new Fr(37n),
    },
planet_arrivals: {
      slot: new Fr(38n),
    }
      } as ContractStorageLayout<'admin' | 'paused' | 'world_radius' | 'planethash_key' | 'spacetype_key' | 'perlin_length_scale' | 'init_perlin_min' | 'init_perlin_max' | 'perlin_threshold_1' | 'perlin_threshold_2' | 'perlin_threshold_3' | 'reveal_cooldown' | 'planet_count' | 'player_count' | 'artifact_count' | 'artifacts' | 'planet_artifact' | 'players' | 'planets' | 'revealed_x' | 'revealed_y' | 'revealed_revealer' | 'revealed_count' | 'revealed_planet_ids' | 'arrival_count' | 'arrivals' | 'planet_arrival_count' | 'planet_arrivals'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** compute_planet_id(x: field, y: field) */
    compute_planet_id: ((x: FieldLike, y: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, world_radius: integer, planethash_key: field, spacetype_key: field, perlin_length_scale: integer, init_perlin_min: integer, init_perlin_max: integer) */
    constructor: ((admin: AztecAddressLike, world_radius: (bigint | number), planethash_key: FieldLike, spacetype_key: FieldLike, perlin_length_scale: (bigint | number), init_perlin_min: (bigint | number), init_perlin_max: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** find_artifact(x: field, y: field, planet_id: field) */
    find_artifact: ((x: FieldLike, y: FieldLike, planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_artifact(artifact_id: field) */
    get_artifact: ((artifact_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_artifact_count() */
    get_artifact_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_game_config() */
    get_game_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_planet_artifact(planet_id: field) */
    get_planet_artifact: ((planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_planet_count() */
    get_planet_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_planet_defense(planet_id: field) */
    get_planet_defense: ((planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_planet_owner(planet_id: field) */
    get_planet_owner: ((planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_planet_perlin(planet_id: field) */
    get_planet_perlin: ((planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_planet_range(planet_id: field) */
    get_planet_range: ((planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_planet_speed(planet_id: field) */
    get_planet_speed: ((planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_player_count() */
    get_player_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_player_home_planet(player: struct) */
    get_player_home_planet: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_revealed_coords(planet_id: field) */
    get_revealed_coords: ((planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_world_radius() */
    get_world_radius: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_player(x: field, y: field) */
    initialize_player: ((x: FieldLike, y: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_paused() */
    is_paused: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_planet_initialized(planet_id: field) */
    is_planet_initialized: ((planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_player_initialized(player: struct) */
    is_player_initialized: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** move_planet(from_x: field, from_y: field, to_x: field, to_y: field, from_planet_id: field, to_planet_id: field, energy_sent: integer, silver_sent: integer) */
    move_planet: ((from_x: FieldLike, from_y: FieldLike, to_x: FieldLike, to_y: FieldLike, from_planet_id: FieldLike, to_planet_id: FieldLike, energy_sent: (bigint | number), silver_sent: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pause() */
    pause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** refresh_planet(planet_id: field) */
    refresh_planet: ((planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** reveal_location(x: field, y: field, planet_id: field) */
    reveal_location: ((x: FieldLike, y: FieldLike, planet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unpause() */
    unpause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** upgrade_planet(planet_id: field, branch: integer) */
    upgrade_planet: ((planet_id: FieldLike, branch: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { PlayerInitialized: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, PlanetUpgraded: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, PlanetMoved: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, LocationRevealed: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, ArtifactFound: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      PlayerInitialized: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "player",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "home_planet",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "DarkForest::PlayerInitialized"
},
        eventSelector: EventSelector.fromString("0x7616d9bd"),
        fieldNames: ["player","home_planet"],
      },
PlanetUpgraded: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "planet_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "branch",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 8
            }
        },
        {
            "name": "new_level",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 8
            }
        }
    ],
    "path": "DarkForest::PlanetUpgraded"
},
        eventSelector: EventSelector.fromString("0x1034c89f"),
        fieldNames: ["planet_id","branch","new_level"],
      },
PlanetMoved: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "to",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "owner",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "distance",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 64
            }
        }
    ],
    "path": "DarkForest::PlanetMoved"
},
        eventSelector: EventSelector.fromString("0x28bfb15e"),
        fieldNames: ["from","to","owner","distance"],
      },
LocationRevealed: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "planet_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "x",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "y",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "revealer",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        }
    ],
    "path": "DarkForest::LocationRevealed"
},
        eventSelector: EventSelector.fromString("0x33226321"),
        fieldNames: ["planet_id","x","y","revealer"],
      },
ArtifactFound: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "planet_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "artifact_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "artifact_type",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 8
            }
        },
        {
            "name": "rarity",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 8
            }
        },
        {
            "name": "discoverer",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        }
    ],
    "path": "DarkForest::ArtifactFound"
},
        eventSelector: EventSelector.fromString("0x0712098f"),
        fieldNames: ["planet_id","artifact_id","artifact_type","rarity","discoverer"],
      }
    };
  }
  
}
